apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow-argo

resources:
  - secrets/airflow-fernet-secret.yml

helmCharts:
- name: airflow
  namespace: airflow-argo
  releaseName: airflow
  repo: https://airflow.apache.org
  version: 1.12.0
  valuesFile: config/helm.values.yml