images:
  airflow:
    repository: apache/airflow
    tag: 2.9.1
    pullPolicy: IfNotPresent

# Webserver service settings
webserver:
  service:
    type: NodePort
    ports:
      - port: 8080
        targetPort: 8080
        nodePort: 30080  # Porta externa do NodePort

secrets:
  fernetKey: "WmHD2ZUvHTCieMSCGjkzZfMlHvvlT2Z6AB7ViLDaELg="

# Airflow configurations
config:
  AIRFLOW__CORE__EXECUTOR:
    value: "CeleryExecutor"
  AIRFLOW__CORE__FERNET_KEY:
    valueFrom:
      secretKeyRef:
        name: airflow-fernet-key
        key: fernetKey  # Refere-se ao Secret criado no Kubernetes
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION:
    value: false
  AIRFLOW__CORE__LOAD_EXAMPLES:
    value: true

# Users - Admin default login
users:
  - username: admin
    password: admin  # Not recommended for prod!
    role: Admin
    email: admin@example.com
    firstName: Admin
    lastName: User

# Postgresql DB (optional: could use external DB in future)
postgresql:
  enabled: true
  auth:
    postgresPassword: airflow
    username: airflow
    password: airflow
    database: airflow

# Redis for Celery executor (disabled if using LocalExecutor)
redis:
  enabled: true

# Flower (task monitor) optional
flower:
  enabled: false

# Triggerer is required for newer versions of Airflow
triggerer:
  replicas: 1

# Scheduler config
scheduler:
  replicas: 1

# Logs (can be enhanced with volumeMounts later)
logs:
  persistence:
    enabled: false

# Persistence for DAGs (use emptyDir for dev)
dags:
  persistence:
    enabled: false

# For dev only: expose ingress or service externally via NodePort or Ingress
ingress:
  enabled: false
