images:
  airflow:
    repository: apache/airflow
    tag: 2.9.1  # ou outra versão estável que você queira
    pullPolicy: IfNotPresent

# registry:
#   secretName: "gitlab-registry-token"

# Basic Airflow Helm Chart configuration for local dev environment

# Webserver service settings
webserver:
  service:
    type: NodePort
    nodePort: 30080  # Minikube-friendly port

# Airflow configurations
config:
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  AIRFLOW__CORE__FERNET_KEY: "your-fernet-key"  # use openssl rand -base64 32
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
  AIRFLOW__CORE__LOAD_EXAMPLES: "true"
  

# Users - Admin default login
users:
  - username: admin
    password: admin  # Not recommended for prod!
    role: Admin
    email: admin@example.com
    firstName: Admin
    lastName: User

# Postgresql DB (optional: could use external DB in future)
postgresql:
  enabled: true
  postgresqlPassword: airflow

# Redis for Celery executor (disabled if using LocalExecutor)
redis:
  enabled: false

# Flower (task monitor) optional
flower:
  enabled: false

# Triggerer is required for newer versions of Airflow
triggerer:
  replicas: 1

# Scheduler config
scheduler:
  replicas: 1

# Workers config - not used in LocalExecutor but required by chart
workers:
  enabled: false

# Logs (can be enhanced with volumeMounts later)
logs:
  persistence:
    enabled: false

# Persistence for DAGs (use emptyDir for dev)
dags:
  persistence:
    enabled: false

# For dev only: expose ingress or service externally via NodePort or Ingress
ingress:
  enabled: false